package app.qlcv.entities;
// Generated Feb 20, 2021 4:59:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SysUserDefineFields generated by hbm2java
 */
public class SysUserDefineFields  implements java.io.Serializable {


     private int id;
     private int versionTime;
     private Date creationDate;
     private Date lastUpdateDate;
     private Integer userDefineId;
     private Integer fieldType;
     private Integer displayOrder;
     private Character activeInd;
     private Integer displaySection;
     private Character mandatoryInd;
     private String code;
     private String field;
     private String validation;
     private String createBy;
     private String lastUpdateBy;
     private String readOnlyInd;

    public SysUserDefineFields() {
    }

	
    public SysUserDefineFields(int id, int versionTime, Date creationDate, Date lastUpdateDate) {
        this.id = id;
        this.versionTime = versionTime;
        this.creationDate = creationDate;
        this.lastUpdateDate = lastUpdateDate;
    }
    public SysUserDefineFields(int id, int versionTime, Date creationDate, Date lastUpdateDate, Integer userDefineId, Integer fieldType, Integer displayOrder, Character activeInd, Integer displaySection, Character mandatoryInd, String code, String field, String validation, String createBy, String lastUpdateBy, String readOnlyInd) {
       this.id = id;
       this.versionTime = versionTime;
       this.creationDate = creationDate;
       this.lastUpdateDate = lastUpdateDate;
       this.userDefineId = userDefineId;
       this.fieldType = fieldType;
       this.displayOrder = displayOrder;
       this.activeInd = activeInd;
       this.displaySection = displaySection;
       this.mandatoryInd = mandatoryInd;
       this.code = code;
       this.field = field;
       this.validation = validation;
       this.createBy = createBy;
       this.lastUpdateBy = lastUpdateBy;
       this.readOnlyInd = readOnlyInd;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getVersionTime() {
        return this.versionTime;
    }
    
    public void setVersionTime(int versionTime) {
        this.versionTime = versionTime;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Integer getUserDefineId() {
        return this.userDefineId;
    }
    
    public void setUserDefineId(Integer userDefineId) {
        this.userDefineId = userDefineId;
    }
    public Integer getFieldType() {
        return this.fieldType;
    }
    
    public void setFieldType(Integer fieldType) {
        this.fieldType = fieldType;
    }
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }
    
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }
    public Character getActiveInd() {
        return this.activeInd;
    }
    
    public void setActiveInd(Character activeInd) {
        this.activeInd = activeInd;
    }
    public Integer getDisplaySection() {
        return this.displaySection;
    }
    
    public void setDisplaySection(Integer displaySection) {
        this.displaySection = displaySection;
    }
    public Character getMandatoryInd() {
        return this.mandatoryInd;
    }
    
    public void setMandatoryInd(Character mandatoryInd) {
        this.mandatoryInd = mandatoryInd;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getField() {
        return this.field;
    }
    
    public void setField(String field) {
        this.field = field;
    }
    public String getValidation() {
        return this.validation;
    }
    
    public void setValidation(String validation) {
        this.validation = validation;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public String getLastUpdateBy() {
        return this.lastUpdateBy;
    }
    
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }
    public String getReadOnlyInd() {
        return this.readOnlyInd;
    }
    
    public void setReadOnlyInd(String readOnlyInd) {
        this.readOnlyInd = readOnlyInd;
    }




}


