package app.qlcv.entities;
// Generated Feb 20, 2021 4:59:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SysUdfFieldValue generated by hbm2java
 */
public class SysUdfFieldValue  implements java.io.Serializable {


     private int id;
     private int versionTime;
     private String createBy;
     private Date creationDate;
     private String lastUpdateBy;
     private Date lastUpdateDate;
     private Integer refId;
     private String refKey;
     private Integer sysUdfFieldId;
     private String extValue1;
     private String extValue2;
     private String extValue3;
     private String extValue4;
     private String extValue5;
     private Integer blockIndex;
     private String fieldValue;
     private String status;

    public SysUdfFieldValue() {
    }

	
    public SysUdfFieldValue(int id, int versionTime, String createBy, Date creationDate, String lastUpdateBy, Date lastUpdateDate) {
        this.id = id;
        this.versionTime = versionTime;
        this.createBy = createBy;
        this.creationDate = creationDate;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateDate = lastUpdateDate;
    }
    public SysUdfFieldValue(int id, int versionTime, String createBy, Date creationDate, String lastUpdateBy, Date lastUpdateDate, Integer refId, String refKey, Integer sysUdfFieldId, String extValue1, String extValue2, String extValue3, String extValue4, String extValue5, Integer blockIndex, String fieldValue) {
       this.id = id;
       this.versionTime = versionTime;
       this.createBy = createBy;
       this.creationDate = creationDate;
       this.lastUpdateBy = lastUpdateBy;
       this.lastUpdateDate = lastUpdateDate;
       this.refId = refId;
       this.refKey = refKey;
       this.sysUdfFieldId = sysUdfFieldId;
       this.extValue1 = extValue1;
       this.extValue2 = extValue2;
       this.extValue3 = extValue3;
       this.extValue4 = extValue4;
       this.extValue5 = extValue5;
       this.blockIndex = blockIndex;
       this.fieldValue = fieldValue;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getVersionTime() {
        return this.versionTime;
    }
    
    public void setVersionTime(int versionTime) {
        this.versionTime = versionTime;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getLastUpdateBy() {
        return this.lastUpdateBy;
    }
    
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Integer getRefId() {
        return this.refId;
    }
    
    public void setRefId(Integer refId) {
        this.refId = refId;
    }
    public String getRefKey() {
        return this.refKey;
    }
    
    public void setRefKey(String refKey) {
        this.refKey = refKey;
    }
    public Integer getSysUdfFieldId() {
        return this.sysUdfFieldId;
    }
    
    public void setSysUdfFieldId(Integer sysUdfFieldId) {
        this.sysUdfFieldId = sysUdfFieldId;
    }
    public String getExtValue1() {
        return this.extValue1;
    }
    
    public void setExtValue1(String extValue1) {
        this.extValue1 = extValue1;
    }
    public String getExtValue2() {
        return this.extValue2;
    }
    
    public void setExtValue2(String extValue2) {
        this.extValue2 = extValue2;
    }
    public String getExtValue3() {
        return this.extValue3;
    }
    
    public void setExtValue3(String extValue3) {
        this.extValue3 = extValue3;
    }
    public String getExtValue4() {
        return this.extValue4;
    }
    
    public void setExtValue4(String extValue4) {
        this.extValue4 = extValue4;
    }
    public String getExtValue5() {
        return this.extValue5;
    }
    
    public void setExtValue5(String extValue5) {
        this.extValue5 = extValue5;
    }
    public Integer getBlockIndex() {
        return this.blockIndex;
    }
    
    public void setBlockIndex(Integer blockIndex) {
        this.blockIndex = blockIndex;
    }
    public String getFieldValue() {
        return this.fieldValue;
    }
    
    public void setFieldValue(String fieldValue) {
        this.fieldValue = fieldValue;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    



}


