package app.qlcv.entities;
// Generated Jun 23, 2020 10:28:56 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TkKpiItemDetailRating generated by hbm2java
 */
public class TkKpiItemDetailRating  implements java.io.Serializable {


     private Integer id;
     private TkKpiItemDetail tkKpiItemDetail;
     private String createBy;
     private String lastUpdateBy;
     private Date createDate;
     private Date lastUpdateDate;
     private Integer month;
     private Integer quater;
     private Integer year;
     private Double trongSo;
     private Double tyLeThucHien;
     private Double ketQuaThucHien;
     private String status;

     private String kpiDetailRatingName;
     private double kpiItem;
    public TkKpiItemDetailRating() {
    }

    public TkKpiItemDetailRating(TkKpiItemDetail tkKpiItemDetail, String createBy, String lastUpdateBy, Date createDate, Date lastUpdateDate, Integer month, Integer quater, Integer year, Double trongSo, Double tyLeThucHien, Double ketQuaThucHien, String status) {
       this.tkKpiItemDetail = tkKpiItemDetail;
       this.createBy = createBy;
       this.lastUpdateBy = lastUpdateBy;
       this.createDate = createDate;
       this.lastUpdateDate = lastUpdateDate;
       this.month = month;
       this.quater = quater;
       this.year = year;
       this.trongSo = trongSo;
       this.tyLeThucHien = tyLeThucHien;
       this.ketQuaThucHien = ketQuaThucHien;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TkKpiItemDetail getTkKpiItemDetail() {
        return this.tkKpiItemDetail;
    }
    
    public void setTkKpiItemDetail(TkKpiItemDetail tkKpiItemDetail) {
        this.tkKpiItemDetail = tkKpiItemDetail;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public String getLastUpdateBy() {
        return this.lastUpdateBy;
    }
    
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Integer getMonth() {
        return this.month;
    }
    
    public void setMonth(Integer month) {
        this.month = month;
    }
    public Integer getQuater() {
        return this.quater;
    }
    
    public void setQuater(Integer quater) {
        this.quater = quater;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Double getTrongSo() {
        return this.trongSo;
    }
    
    public void setTrongSo(Double trongSo) {
        this.trongSo = trongSo;
    }
    public Double getTyLeThucHien() {
        return this.tyLeThucHien;
    }
    
    public void setTyLeThucHien(Double tyLeThucHien) {
        this.tyLeThucHien = tyLeThucHien;
    }
    public Double getKetQuaThucHien() {
        return this.ketQuaThucHien;
    }
    
    public void setKetQuaThucHien(Double ketQuaThucHien) {
        this.ketQuaThucHien = ketQuaThucHien;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getKpiDetailRatingName() {
        return kpiDetailRatingName;
    }

    public void setKpiDetailRatingName(String kpiDetailRatingName) {
        this.kpiDetailRatingName = kpiDetailRatingName;
    }

    public double getKpiItem() {
        return kpiItem;
    }

    public void setKpiItem(double kpiItem) {
        this.kpiItem = kpiItem;
    }
    



}


