package app.qlcv.entities;
// Generated Jun 18, 2020 5:55:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TkKpiItemSetting generated by hbm2java
 */
public class TkKpiItemSetting  implements java.io.Serializable {


     private Integer id;
     private TkKpiTypeSetting tkKpiTypeSetting;
     private String createBy;
     private String lastUpdateBy;
     private Date createDate;
     private Date lastUpdateDate;
     private String kpiName;
     private String kpiDesc;
     private Double item;
     private String donViTinh;
     private Double trongSo;
     private String tanSuatDanhGia;
     private String thoiDiemDanhGia;
     private String status;
     private String type;
     private String isKetQua;

    public TkKpiItemSetting() {
    }

	
    public TkKpiItemSetting(TkKpiTypeSetting tkKpiTypeSetting) {
        this.tkKpiTypeSetting = tkKpiTypeSetting;
    }
    public TkKpiItemSetting(TkKpiTypeSetting tkKpiTypeSetting, String createBy, String lastUpdateBy, Date createDate, Date lastUpdateDate, String kpiName, String kpiDesc, Double item, String donViTinh, Double trongSo, String tanSuatDanhGia, String thoiDiemDanhGia, String status, String type, String isKetQua) {
       this.tkKpiTypeSetting = tkKpiTypeSetting;
       this.createBy = createBy;
       this.lastUpdateBy = lastUpdateBy;
       this.createDate = createDate;
       this.lastUpdateDate = lastUpdateDate;
       this.kpiName = kpiName;
       this.kpiDesc = kpiDesc;
       this.item = item;
       this.donViTinh = donViTinh;
       this.trongSo = trongSo;
       this.tanSuatDanhGia = tanSuatDanhGia;
       this.thoiDiemDanhGia = thoiDiemDanhGia;
       this.status = status;
       this.type = type;
       this.isKetQua = isKetQua;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TkKpiTypeSetting getTkKpiTypeSetting() {
        return this.tkKpiTypeSetting;
    }
    
    public void setTkKpiTypeSetting(TkKpiTypeSetting tkKpiTypeSetting) {
        this.tkKpiTypeSetting = tkKpiTypeSetting;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public String getLastUpdateBy() {
        return this.lastUpdateBy;
    }
    
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public String getKpiName() {
        return this.kpiName;
    }
    
    public void setKpiName(String kpiName) {
        this.kpiName = kpiName;
    }
    public String getKpiDesc() {
        return this.kpiDesc;
    }
    
    public void setKpiDesc(String kpiDesc) {
        this.kpiDesc = kpiDesc;
    }
    public Double getItem() {
        return this.item;
    }
    
    public void setItem(Double item) {
        this.item = item;
    }
    public String getDonViTinh() {
        return this.donViTinh;
    }
    
    public void setDonViTinh(String donViTinh) {
        this.donViTinh = donViTinh;
    }
    public Double getTrongSo() {
        return this.trongSo;
    }
    
    public void setTrongSo(Double trongSo) {
        this.trongSo = trongSo;
    }
    public String getTanSuatDanhGia() {
        return this.tanSuatDanhGia;
    }
    
    public void setTanSuatDanhGia(String tanSuatDanhGia) {
        this.tanSuatDanhGia = tanSuatDanhGia;
    }
    public String getThoiDiemDanhGia() {
        return this.thoiDiemDanhGia;
    }
    
    public void setThoiDiemDanhGia(String thoiDiemDanhGia) {
        this.thoiDiemDanhGia = thoiDiemDanhGia;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getIsKetQua() {
        return this.isKetQua;
    }
    
    public void setIsKetQua(String isKetQua) {
        this.isKetQua = isKetQua;
    }




}


