package app.qlcv.entities;
// Generated Mar 4, 2021 11:21:49 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TkKpiTypeSetting generated by hbm2java
 */
public class TkKpiTypeSetting  implements java.io.Serializable {


     private Integer id;
     private TkDepartment tkDepartment;
     private String createBy;
     private String lastUpdateBy;
     private Date createDate;
     private Date lastUpdateDate;
     private String kpiName;
     private String kpiDesc;
     private Double trongSoKpiPhongban;
     private Double trongSoKpiThuongxuyen;
     private Double trongSoKpiDotxuat;
     private String status;
     private String apDung;
     private Set tkKpiItemSettings = new HashSet(0);

    public TkKpiTypeSetting() {
    }

	
    public TkKpiTypeSetting(TkDepartment tkDepartment) {
        this.tkDepartment = tkDepartment;
    }
    public TkKpiTypeSetting(TkDepartment tkDepartment, String createBy, String lastUpdateBy, Date createDate, Date lastUpdateDate, String kpiName, String kpiDesc, Double trongSoKpiPhongban, Double trongSoKpiThuongxuyen, Double trongSoKpiDotxuat, String status, String apDung, Set tkKpiItemSettings) {
       this.tkDepartment = tkDepartment;
       this.createBy = createBy;
       this.lastUpdateBy = lastUpdateBy;
       this.createDate = createDate;
       this.lastUpdateDate = lastUpdateDate;
       this.kpiName = kpiName;
       this.kpiDesc = kpiDesc;
       this.trongSoKpiPhongban = trongSoKpiPhongban;
       this.trongSoKpiThuongxuyen = trongSoKpiThuongxuyen;
       this.trongSoKpiDotxuat = trongSoKpiDotxuat;
       this.status = status;
       this.apDung = apDung;
       this.tkKpiItemSettings = tkKpiItemSettings;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TkDepartment getTkDepartment() {
        return this.tkDepartment;
    }
    
    public void setTkDepartment(TkDepartment tkDepartment) {
        this.tkDepartment = tkDepartment;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public String getLastUpdateBy() {
        return this.lastUpdateBy;
    }
    
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public String getKpiName() {
        return this.kpiName;
    }
    
    public void setKpiName(String kpiName) {
        this.kpiName = kpiName;
    }
    public String getKpiDesc() {
        return this.kpiDesc;
    }
    
    public void setKpiDesc(String kpiDesc) {
        this.kpiDesc = kpiDesc;
    }
    public Double getTrongSoKpiPhongban() {
        return this.trongSoKpiPhongban;
    }
    
    public void setTrongSoKpiPhongban(Double trongSoKpiPhongban) {
        this.trongSoKpiPhongban = trongSoKpiPhongban;
    }
    public Double getTrongSoKpiThuongxuyen() {
        return this.trongSoKpiThuongxuyen;
    }
    
    public void setTrongSoKpiThuongxuyen(Double trongSoKpiThuongxuyen) {
        this.trongSoKpiThuongxuyen = trongSoKpiThuongxuyen;
    }
    public Double getTrongSoKpiDotxuat() {
        return this.trongSoKpiDotxuat;
    }
    
    public void setTrongSoKpiDotxuat(Double trongSoKpiDotxuat) {
        this.trongSoKpiDotxuat = trongSoKpiDotxuat;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getApDung() {
        return this.apDung;
    }
    
    public void setApDung(String apDung) {
        this.apDung = apDung;
    }
    public Set getTkKpiItemSettings() {
        return this.tkKpiItemSettings;
    }
    
    public void setTkKpiItemSettings(Set tkKpiItemSettings) {
        this.tkKpiItemSettings = tkKpiItemSettings;
    }




}


