package app.qlcv.entities;
// Generated Jun 23, 2020 10:28:56 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TkKpiItemDetail generated by hbm2java
 */
public class TkKpiItemDetail implements java.io.Serializable {

    private Integer id;
    private TkKpiItem tkKpiItem;
    private String createBy;
    private String lastUpdateBy;
    private Date createDate;
    private Date lastUpdateDate;
    private String kpiName;
    private String kpiDesc;
    private Double item;
    private String donViTinh;
    private String tanSuatDanhGia;
    private Double trongSo;
    private Double tyLeThucHien = 0.0;
    private Double ketQuaThucHien;
    private String status;
    private Integer refId;
    private Integer month;
    private String source;
    private String refIdSource;
    private Set tkKpiItemDetailRatings = new HashSet(0);

    public TkKpiItemDetail() {
    }

    public TkKpiItemDetail(TkKpiItem tkKpiItem, String createBy, String lastUpdateBy, Date createDate, Date lastUpdateDate, Double item, String donViTinh, String tanSuatDanhGia, Double trongSo, Double tyLeThucHien, Double ketQuaThucHien, String status, Set tkKpiItemDetailRatings) {
        this.tkKpiItem = tkKpiItem;
        this.createBy = createBy;
        this.lastUpdateBy = lastUpdateBy;
        this.createDate = createDate;
        this.lastUpdateDate = lastUpdateDate;
        this.item = item;
        this.donViTinh = donViTinh;
        this.tanSuatDanhGia = tanSuatDanhGia;
        this.trongSo = trongSo;
        this.tyLeThucHien = tyLeThucHien;
        this.ketQuaThucHien = ketQuaThucHien;
        this.status = status;
        this.tkKpiItemDetailRatings = tkKpiItemDetailRatings;
    }

    public String getKpiName() {
        return kpiName;
    }

    public void setKpiName(String kpiName) {
        this.kpiName = kpiName;
    }

    public String getKpiDesc() {
        return kpiDesc;
    }

    public void setKpiDesc(String kpiDesc) {
        this.kpiDesc = kpiDesc;
    }

    
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public TkKpiItem getTkKpiItem() {
        return this.tkKpiItem;
    }

    public void setTkKpiItem(TkKpiItem tkKpiItem) {
        this.tkKpiItem = tkKpiItem;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public String getLastUpdateBy() {
        return this.lastUpdateBy;
    }

    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    public Double getItem() {
        return this.item;
    }

    public void setItem(Double item) {
        this.item = item;
    }

    public String getDonViTinh() {
        return this.donViTinh;
    }

    public void setDonViTinh(String donViTinh) {
        this.donViTinh = donViTinh;
    }

    public String getTanSuatDanhGia() {
        return this.tanSuatDanhGia;
    }

    public void setTanSuatDanhGia(String tanSuatDanhGia) {
        this.tanSuatDanhGia = tanSuatDanhGia;
    }

    public Double getTrongSo() {
        return this.trongSo;
    }

    public void setTrongSo(Double trongSo) {
        this.trongSo = trongSo;
    }

    public Double getTyLeThucHien() {
        return this.tyLeThucHien;
    }

    public void setTyLeThucHien(Double tyLeThucHien) {
        this.tyLeThucHien = tyLeThucHien;
    }

    public Double getKetQuaThucHien() {
        return this.ketQuaThucHien;
    }

    public void setKetQuaThucHien(Double ketQuaThucHien) {
        this.ketQuaThucHien = ketQuaThucHien;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Set getTkKpiItemDetailRatings() {
        return this.tkKpiItemDetailRatings;
    }

    public void setTkKpiItemDetailRatings(Set tkKpiItemDetailRatings) {
        this.tkKpiItemDetailRatings = tkKpiItemDetailRatings;
    }

    public Integer getRefId() {
        return refId;
    }

    public void setRefId(Integer refId) {
        this.refId = refId;
    }

    public Integer getMonth() {
        return month;
    }

    public void setMonth(Integer month) {
        this.month = month;
    }



    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getRefIdSource() {
        return refIdSource;
    }

    public void setRefIdSource(String refIdSource) {
        this.refIdSource = refIdSource;
    }

   

    
}
