package app.qlcv.entities;
// Generated Feb 20, 2021 4:59:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TkWsTaskChecklist generated by hbm2java
 */
public class TkWsTaskChecklist  implements java.io.Serializable {


     private int id;
     private TkWsTask tkWsTask;
     private String createBy;
     private String lastUdpateBy;
     private Date createDate;
     private Date lastUdpateDate;
     private String checkListName;
     private String checkListDesc;
     private String checkListStatus;
     private Set tkWsTaskChecklistItems = new HashSet(0);

    public TkWsTaskChecklist() {
    }

	
    public TkWsTaskChecklist(int id, TkWsTask tkWsTask) {
        this.id = id;
        this.tkWsTask = tkWsTask;
    }
    public TkWsTaskChecklist(int id, TkWsTask tkWsTask, String createBy, String lastUdpateBy, Date createDate, Date lastUdpateDate, String checkListName, String checkListDesc, String checkListStatus, Set tkWsTaskChecklistItems) {
       this.id = id;
       this.tkWsTask = tkWsTask;
       this.createBy = createBy;
       this.lastUdpateBy = lastUdpateBy;
       this.createDate = createDate;
       this.lastUdpateDate = lastUdpateDate;
       this.checkListName = checkListName;
       this.checkListDesc = checkListDesc;
       this.checkListStatus = checkListStatus;
       this.tkWsTaskChecklistItems = tkWsTaskChecklistItems;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TkWsTask getTkWsTask() {
        return this.tkWsTask;
    }
    
    public void setTkWsTask(TkWsTask tkWsTask) {
        this.tkWsTask = tkWsTask;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public String getLastUdpateBy() {
        return this.lastUdpateBy;
    }
    
    public void setLastUdpateBy(String lastUdpateBy) {
        this.lastUdpateBy = lastUdpateBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getLastUdpateDate() {
        return this.lastUdpateDate;
    }
    
    public void setLastUdpateDate(Date lastUdpateDate) {
        this.lastUdpateDate = lastUdpateDate;
    }
    public String getCheckListName() {
        return this.checkListName;
    }
    
    public void setCheckListName(String checkListName) {
        this.checkListName = checkListName;
    }
    public String getCheckListDesc() {
        return this.checkListDesc;
    }
    
    public void setCheckListDesc(String checkListDesc) {
        this.checkListDesc = checkListDesc;
    }
    public String getCheckListStatus() {
        return this.checkListStatus;
    }
    
    public void setCheckListStatus(String checkListStatus) {
        this.checkListStatus = checkListStatus;
    }
    public Set getTkWsTaskChecklistItems() {
        return this.tkWsTaskChecklistItems;
    }
    
    public void setTkWsTaskChecklistItems(Set tkWsTaskChecklistItems) {
        this.tkWsTaskChecklistItems = tkWsTaskChecklistItems;
    }




}


