package app.qlcv.entities;
// Generated Mar 1, 2021 10:49:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TkWsFolder generated by hbm2java
 */
public class TkWsFolder  implements java.io.Serializable {


     private Integer id;
     private String folderName;
     private String folderStatus;
     private String folderDesc;
     private String isMilestones;
     private BigDecimal milestonesTienkhoan;
     private Date milestinesStartDate;
     private Date milestonesEndDate;
     private Date milestonesCloseDate;
     private String status;
     private Set tkWsTasklists = new HashSet(0);

    public TkWsFolder() {
    }

    public TkWsFolder(String folderName, String folderStatus, String folderDesc, String isMilestones, BigDecimal milestonesTienkhoan, Date milestinesStartDate, Date milestonesEndDate, Set tkWsTasklists) {
       this.folderName = folderName;
       this.folderStatus = folderStatus;
       this.folderDesc = folderDesc;
       this.isMilestones = isMilestones;
       this.milestonesTienkhoan = milestonesTienkhoan;
       this.milestinesStartDate = milestinesStartDate;
       this.milestonesEndDate = milestonesEndDate;
       this.tkWsTasklists = tkWsTasklists;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFolderName() {
        return this.folderName;
    }
    
    public void setFolderName(String folderName) {
        this.folderName = folderName;
    }
    public String getFolderStatus() {
        return this.folderStatus;
    }
    
    public void setFolderStatus(String folderStatus) {
        this.folderStatus = folderStatus;
    }
    public String getFolderDesc() {
        return this.folderDesc;
    }
    
    public void setFolderDesc(String folderDesc) {
        this.folderDesc = folderDesc;
    }
    public String getIsMilestones() {
        return this.isMilestones;
    }
    
    public void setIsMilestones(String isMilestones) {
        this.isMilestones = isMilestones;
    }
    public BigDecimal getMilestonesTienkhoan() {
        return this.milestonesTienkhoan;
    }
    
    public void setMilestonesTienkhoan(BigDecimal milestonesTienkhoan) {
        this.milestonesTienkhoan = milestonesTienkhoan;
    }
    public Date getMilestinesStartDate() {
        return this.milestinesStartDate;
    }
    
    public void setMilestinesStartDate(Date milestinesStartDate) {
        this.milestinesStartDate = milestinesStartDate;
    }
    public Date getMilestonesEndDate() {
        return this.milestonesEndDate;
    }
    
    public void setMilestonesEndDate(Date milestonesEndDate) {
        this.milestonesEndDate = milestonesEndDate;
    }
    public Set getTkWsTasklists() {
        return this.tkWsTasklists;
    }
    
    public void setTkWsTasklists(Set tkWsTasklists) {
        this.tkWsTasklists = tkWsTasklists;
    }

    public Date getMilestonesCloseDate() {
        return milestonesCloseDate;
    }

    public void setMilestonesCloseDate(Date milestonesCloseDate) {
        this.milestonesCloseDate = milestonesCloseDate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }




}


