package app.qlcv.entities;
// Generated Feb 20, 2021 4:59:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TkWsTaskChecklistItem generated by hbm2java
 */
public class TkWsTaskChecklistItem  implements java.io.Serializable {


     private int id;
     private TkWsTaskChecklist tkWsTaskChecklist;
     private String createBy;
     private String lastUpdateBy;
     private Date createDate;
     private Date lastUpdateDate;
     private String itemName;
     private String itemStatus;
     private Integer itemAssignee;

    public TkWsTaskChecklistItem() {
    }

	
    public TkWsTaskChecklistItem(int id, TkWsTaskChecklist tkWsTaskChecklist) {
        this.id = id;
        this.tkWsTaskChecklist = tkWsTaskChecklist;
    }
    public TkWsTaskChecklistItem(int id, TkWsTaskChecklist tkWsTaskChecklist, String createBy, String lastUpdateBy, Date createDate, Date lastUpdateDate, String itemName, String itemStatus, Integer itemAssignee) {
       this.id = id;
       this.tkWsTaskChecklist = tkWsTaskChecklist;
       this.createBy = createBy;
       this.lastUpdateBy = lastUpdateBy;
       this.createDate = createDate;
       this.lastUpdateDate = lastUpdateDate;
       this.itemName = itemName;
       this.itemStatus = itemStatus;
       this.itemAssignee = itemAssignee;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TkWsTaskChecklist getTkWsTaskChecklist() {
        return this.tkWsTaskChecklist;
    }
    
    public void setTkWsTaskChecklist(TkWsTaskChecklist tkWsTaskChecklist) {
        this.tkWsTaskChecklist = tkWsTaskChecklist;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public String getLastUpdateBy() {
        return this.lastUpdateBy;
    }
    
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public String getItemStatus() {
        return this.itemStatus;
    }
    
    public void setItemStatus(String itemStatus) {
        this.itemStatus = itemStatus;
    }
    public Integer getItemAssignee() {
        return this.itemAssignee;
    }
    
    public void setItemAssignee(Integer itemAssignee) {
        this.itemAssignee = itemAssignee;
    }




}


