package app.qlcv.entities;
// Generated Feb 20, 2021 4:59:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TkWsPeople generated by hbm2java
 */
public class TkWsPeople  implements java.io.Serializable {


     private int id;
     private TkWorkspace tkWorkspace;
     private String roleWorkspace;
     private String status;
     private Integer userId;
     private Set tkWsTeamses = new HashSet(0);

    public TkWsPeople() {
    }

	
    public TkWsPeople(int id, TkWorkspace tkWorkspace) {
        this.id = id;
        this.tkWorkspace = tkWorkspace;
    }
    public TkWsPeople(int id, TkWorkspace tkWorkspace, String roleWorkspace, String status, Integer userId, Set tkWsTeamses) {
       this.id = id;
       this.tkWorkspace = tkWorkspace;
       this.roleWorkspace = roleWorkspace;
       this.status = status;
       this.userId = userId;
       this.tkWsTeamses = tkWsTeamses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TkWorkspace getTkWorkspace() {
        return this.tkWorkspace;
    }
    
    public void setTkWorkspace(TkWorkspace tkWorkspace) {
        this.tkWorkspace = tkWorkspace;
    }
    public String getRoleWorkspace() {
        return this.roleWorkspace;
    }
    
    public void setRoleWorkspace(String roleWorkspace) {
        this.roleWorkspace = roleWorkspace;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Set getTkWsTeamses() {
        return this.tkWsTeamses;
    }
    
    public void setTkWsTeamses(Set tkWsTeamses) {
        this.tkWsTeamses = tkWsTeamses;
    }




}


