package app.qlcv.entities;
// Generated Feb 20, 2021 4:59:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TkWsTeams generated by hbm2java
 */
public class TkWsTeams  implements java.io.Serializable {


     private int id;
     private TkWorkspace tkWorkspace;
     private String teamName;
     private String teamDesc;
     private String teamStatus;
     private String createBy;
     private String lastUpdateBy;
     private Date createDate;
     private Date lastUpdateDate;
     private Set tkWsPeoples = new HashSet(0);

    public TkWsTeams() {
    }

	
    public TkWsTeams(int id, TkWorkspace tkWorkspace) {
        this.id = id;
        this.tkWorkspace = tkWorkspace;
    }
    public TkWsTeams(int id, TkWorkspace tkWorkspace, String teamName, String teamDesc, String teamStatus, String createBy, String lastUpdateBy, Date createDate, Date lastUpdateDate, Set tkWsPeoples) {
       this.id = id;
       this.tkWorkspace = tkWorkspace;
       this.teamName = teamName;
       this.teamDesc = teamDesc;
       this.teamStatus = teamStatus;
       this.createBy = createBy;
       this.lastUpdateBy = lastUpdateBy;
       this.createDate = createDate;
       this.lastUpdateDate = lastUpdateDate;
       this.tkWsPeoples = tkWsPeoples;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TkWorkspace getTkWorkspace() {
        return this.tkWorkspace;
    }
    
    public void setTkWorkspace(TkWorkspace tkWorkspace) {
        this.tkWorkspace = tkWorkspace;
    }
    public String getTeamName() {
        return this.teamName;
    }
    
    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }
    public String getTeamDesc() {
        return this.teamDesc;
    }
    
    public void setTeamDesc(String teamDesc) {
        this.teamDesc = teamDesc;
    }
    public String getTeamStatus() {
        return this.teamStatus;
    }
    
    public void setTeamStatus(String teamStatus) {
        this.teamStatus = teamStatus;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public String getLastUpdateBy() {
        return this.lastUpdateBy;
    }
    
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public Set getTkWsPeoples() {
        return this.tkWsPeoples;
    }
    
    public void setTkWsPeoples(Set tkWsPeoples) {
        this.tkWsPeoples = tkWsPeoples;
    }




}


