package app.qlcv.entities;
// Generated Feb 20, 2021 4:59:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TkWsTask generated by hbm2java
 */
public class TkWsTask  implements java.io.Serializable {


     private int id;
     private TkWsTasklist tkWsTasklist;
     private String createBy;
     private String lastUpdateBy;
     private Date createDate;
     private Date lastUpdateDate;
     private String taskName;
     private String taskDesc;
     private String isSubTask;
     private Integer parentTaskId;
     private Integer assigneeUserId;
     private Date startDate;
     private Date dateClose;
     private Date dueDate;
     private Integer priority;
     private String status;
     private Integer timeEstimate;
     private Integer timeEstimateDdl;
     private Long nganSach;
     private Integer nganSachCcy;
     private Long amountPlan;
     private Long amountSpent;
     private Long amountRemain;
     private Integer reviewBy;
     private String refId;
     private String source;
     private String followTask;
     private Long etcAmountPlan;
     private Date etcDatePlan;
     private Long percentCoplete;
     
     private int taskLevel = 0;
     private Set tkWsTaskChecklists = new HashSet(0);

    public TkWsTask() {
    }

	
    public TkWsTask(int id, TkWsTasklist tkWsTasklist, String isSubTask) {
        this.id = id;
        this.tkWsTasklist = tkWsTasklist;
        this.isSubTask = isSubTask;
    }
    public TkWsTask(int id, TkWsTasklist tkWsTasklist, String createBy, String lastUpdateBy, Date createDate, Date lastUpdateDate, String taskName, String taskDesc, String isSubTask, Integer parentTaskId, Integer assigneeUserId, Date startDate, Date dateClose, Date dueDate, Integer priority, String status, Integer timeEstimate, Integer timeEstimateDdl, Long nganSach, Integer nganSachCcy, Long amountSpent, Long amountRemain, Integer reviewBy, Set tkWsTaskChecklists) {
       this.id = id;
       this.tkWsTasklist = tkWsTasklist;
       this.createBy = createBy;
       this.lastUpdateBy = lastUpdateBy;
       this.createDate = createDate;
       this.lastUpdateDate = lastUpdateDate;
       this.taskName = taskName;
       this.taskDesc = taskDesc;
       this.isSubTask = isSubTask;
       this.parentTaskId = parentTaskId;
       this.assigneeUserId = assigneeUserId;
       this.startDate = startDate;
       this.dateClose = dateClose;
       this.dueDate = dueDate;
       this.priority = priority;
       this.status = status;
       this.timeEstimate = timeEstimate;
       this.timeEstimateDdl = timeEstimateDdl;
       this.nganSach = nganSach;
       this.nganSachCcy = nganSachCcy;
       this.amountSpent = amountSpent;
       this.amountRemain = amountRemain;
       this.reviewBy = reviewBy;
       this.tkWsTaskChecklists = tkWsTaskChecklists;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TkWsTasklist getTkWsTasklist() {
        return this.tkWsTasklist;
    }
    
    public void setTkWsTasklist(TkWsTasklist tkWsTasklist) {
        this.tkWsTasklist = tkWsTasklist;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public String getLastUpdateBy() {
        return this.lastUpdateBy;
    }
    
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    public String getTaskName() {
        return taskName;
    }

    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    public String getTaskDesc() {
        return taskDesc;
    }

    public void setTaskDesc(String taskDesc) {
        this.taskDesc = taskDesc;
    }
   
    public String getIsSubTask() {
        return this.isSubTask;
    }
    
    public void setIsSubTask(String isSubTask) {
        this.isSubTask = isSubTask;
    }
    public Integer getParentTaskId() {
        return this.parentTaskId;
    }
    
    public void setParentTaskId(Integer parentTaskId) {
        this.parentTaskId = parentTaskId;
    }
    public Integer getAssigneeUserId() {
        return this.assigneeUserId;
    }
    
    public void setAssigneeUserId(Integer assigneeUserId) {
        this.assigneeUserId = assigneeUserId;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getDateClose() {
        return this.dateClose;
    }
    
    public void setDateClose(Date dateClose) {
        this.dateClose = dateClose;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public Integer getPriority() {
        return this.priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Integer getTimeEstimate() {
        return this.timeEstimate;
    }
    
    public void setTimeEstimate(Integer timeEstimate) {
        this.timeEstimate = timeEstimate;
    }
    public Integer getTimeEstimateDdl() {
        return this.timeEstimateDdl;
    }
    
    public void setTimeEstimateDdl(Integer timeEstimateDdl) {
        this.timeEstimateDdl = timeEstimateDdl;
    }
    public Long getNganSach() {
        return this.nganSach;
    }
    
    public void setNganSach(Long nganSach) {
        this.nganSach = nganSach;
    }
    public Integer getNganSachCcy() {
        return this.nganSachCcy;
    }
    
    public void setNganSachCcy(Integer nganSachCcy) {
        this.nganSachCcy = nganSachCcy;
    }
    public Long getAmountSpent() {
        return this.amountSpent;
    }
    
    public void setAmountSpent(Long amountSpent) {
        this.amountSpent = amountSpent;
    }
    public Long getAmountRemain() {
        return this.amountRemain;
    }
    
    public void setAmountRemain(Long amountRemain) {
        this.amountRemain = amountRemain;
    }
    public Integer getReviewBy() {
        return this.reviewBy;
    }
    
    public void setReviewBy(Integer reviewBy) {
        this.reviewBy = reviewBy;
    }
    public Set getTkWsTaskChecklists() {
        return this.tkWsTaskChecklists;
    }
    
    public void setTkWsTaskChecklists(Set tkWsTaskChecklists) {
        this.tkWsTaskChecklists = tkWsTaskChecklists;
    }

    public String getRefId() {
        return refId;
    }

    public void setRefId(String refId) {
        this.refId = refId;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getFollowTask() {
        return followTask;
    }

    public void setFollowTask(String followTask) {
        this.followTask = followTask;
    }

    public int getTaskLevel() {
        return taskLevel;
    }

    public void setTaskLevel(int taskLevel) {
        this.taskLevel = taskLevel;
    }

    public Long getAmountPlan() {
        return amountPlan;
    }

    public void setAmountPlan(Long amountPlan) {
        this.amountPlan = amountPlan;
    }

    public Long getEtcAmountPlan() {
        return etcAmountPlan;
    }

    public void setEtcAmountPlan(Long etcAmountPlan) {
        this.etcAmountPlan = etcAmountPlan;
    }

    public Date getEtcDatePlan() {
        return etcDatePlan;
    }

    public void setEtcDatePlan(Date etcDatePlan) {
        this.etcDatePlan = etcDatePlan;
    }

    public Long getPercentCoplete() {
        return percentCoplete;
    }

    public void setPercentCoplete(Long percentCoplete) {
        this.percentCoplete = percentCoplete;
    }
    
    

}


