package app.qlcv.entities;
// Generated Mar 1, 2021 11:47:31 AM by Hibernate Tools 4.3.1



/**
 * TkWsTaskRaci generated by hbm2java
 */
public class TkWsTaskRaci  implements java.io.Serializable {


     private Integer id;
     private TkWsTasklist tkWsTasklist;
     private int userId;
     private String raciR;
     private String raciA;
     private String raciC;
     private String raciI;
     private String status;

    public TkWsTaskRaci() {
    }

	
    public TkWsTaskRaci(TkWsTasklist tkWsTasklist, int userId) {
        this.tkWsTasklist = tkWsTasklist;
        this.userId = userId;
    }
    public TkWsTaskRaci(TkWsTasklist tkWsTasklist, int userId, String raciR, String raciA, String raciC, String raciI, String status) {
       this.tkWsTasklist = tkWsTasklist;
       this.userId = userId;
       this.raciR = raciR;
       this.raciA = raciA;
       this.raciC = raciC;
       this.raciI = raciI;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TkWsTasklist getTkWsTasklist() {
        return this.tkWsTasklist;
    }
    
    public void setTkWsTasklist(TkWsTasklist tkWsTasklist) {
        this.tkWsTasklist = tkWsTasklist;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getRaciR() {
        return this.raciR;
    }
    
    public void setRaciR(String raciR) {
        this.raciR = raciR;
    }
    public String getRaciA() {
        return this.raciA;
    }
    
    public void setRaciA(String raciA) {
        this.raciA = raciA;
    }
    public String getRaciC() {
        return this.raciC;
    }
    
    public void setRaciC(String raciC) {
        this.raciC = raciC;
    }
    public String getRaciI() {
        return this.raciI;
    }
    
    public void setRaciI(String raciI) {
        this.raciI = raciI;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


