package app.qlcv.entities;
// Generated Feb 20, 2021 4:59:14 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TkWsTasklist generated by hbm2java
 */
public class TkWsTasklist implements java.io.Serializable {

    private int id;
    private TkWorkspace tkWorkspace;
    private TkWsFolder tkWsFolder;
    private String taskListTitle;
    private String taskListDesc;
    private Integer timeEstimate;
    private Integer timeEstimateDdl;
    private Date dueDate;
    private String priority;
    private String status;
    private String createBy;
    private String lastUpdateBy;
    private Date createDate;
    private Date lastUpdateDate;
    private Set tkWsTaskRacis = new HashSet(0);
    private Set tkWsTasks = new HashSet(0);

    public TkWsTasklist() {
    }

    public TkWsTasklist(int id, TkWorkspace tkWorkspace) {
        this.id = id;
        this.tkWorkspace = tkWorkspace;
    }

    public TkWsTasklist(int id, TkWorkspace tkWorkspace, TkWsFolder tkWsFolder, String taskListTitle, String taskListDesc, Integer timeEstimate, Integer timeEstimateDdl, Date dueDate, String priority, String status, String createBy, String lastUpdateBy, Date createDate, Date lastUpdateDate, Set tkWsTasks) {
        this.id = id;
        this.tkWorkspace = tkWorkspace;
        this.tkWsFolder = tkWsFolder;
        this.taskListTitle = taskListTitle;
        this.taskListDesc = taskListDesc;
        this.timeEstimate = timeEstimate;
        this.timeEstimateDdl = timeEstimateDdl;
        this.dueDate = dueDate;
        this.priority = priority;
        this.status = status;
        this.createBy = createBy;
        this.lastUpdateBy = lastUpdateBy;
        this.createDate = createDate;
        this.lastUpdateDate = lastUpdateDate;
        this.tkWsTasks = tkWsTasks;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public TkWorkspace getTkWorkspace() {
        return this.tkWorkspace;
    }

    public void setTkWorkspace(TkWorkspace tkWorkspace) {
        this.tkWorkspace = tkWorkspace;
    }

    public TkWsFolder getTkWsFolder() {
        return this.tkWsFolder;
    }

    public void setTkWsFolder(TkWsFolder tkWsFolder) {
        this.tkWsFolder = tkWsFolder;
    }

    public String getTaskListTitle() {
        return this.taskListTitle;
    }

    public void setTaskListTitle(String taskListTitle) {
        this.taskListTitle = taskListTitle;
    }

    public String getTaskListDesc() {
        return this.taskListDesc;
    }

    public void setTaskListDesc(String taskListDesc) {
        this.taskListDesc = taskListDesc;
    }

    public Integer getTimeEstimate() {
        return this.timeEstimate;
    }

    public void setTimeEstimate(Integer timeEstimate) {
        this.timeEstimate = timeEstimate;
    }

    public Integer getTimeEstimateDdl() {
        return this.timeEstimateDdl;
    }

    public void setTimeEstimateDdl(Integer timeEstimateDdl) {
        this.timeEstimateDdl = timeEstimateDdl;
    }

    public Date getDueDate() {
        return this.dueDate;
    }

    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    public String getPriority() {
        return this.priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public String getLastUpdateBy() {
        return this.lastUpdateBy;
    }

    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    public Set getTkWsTasks() {
        return this.tkWsTasks;
    }

    public void setTkWsTasks(Set tkWsTasks) {
        this.tkWsTasks = tkWsTasks;
    }

    public Set getTkWsTaskRacis() {
        return this.tkWsTaskRacis;
    }

    public void setTkWsTaskRacis(Set tkWsTaskRacis) {
        this.tkWsTaskRacis = tkWsTaskRacis;
    }

}
